### PR TITLE
support custom name for test folder added

### PR DESCRIPTION
**Pull request by franciscodelgadodev**

### CODE REVIEW

**Comment by Gowiem** [comment]
First time using Qunit and I think this feature would be really useful. I'm about to transition over from Jasmine since Ember explicitly uses Qunit and it would be awesome to keep the same directory structure of `spec/javascripts/`.

**Comment by ghost** [comment]
:+1:

**Comment by elsurudo** [comment]
+1 on this

**Comment by frodsan** [comment]
Done by 32f7cf5783.

**Comment by frodsan** [comment]
This feature is included in [v0.0.6](https://rubygems.org/gems/qunit-rails/versions/0.0.6).

**Pull request closed without merging**
