### PR TITLE
Allows you to create different test suites arbitrarily

### PR DESCRIPTION
**Pull request by Randuin**

### CODE REVIEW

**Comment by jherdman** [comment]
This would be a godsend for an application I'm working on. Is there any chance of getting this merged in?

**Comment by frodsan** [comment]
Could you elaborate what are you trying to do?

**Comment by jherdman** [comment]
Sure. The Rails API I'm working on feeds several Ember apps. The structure looks something like this:

```
app/assets/javascripts
├── app0
├── app1
├── app2
├── app3
└── app4
```

I'm hoping that the ability to create different test suites would allow me to test these apps more easily. As it stands, it seems that the assumption of qunit-rails is that the API is one-to-one with the JavaScript on the front end (which, honestly, is a more sane approach, but is not one I can take at this time).

**Comment by alkrauss48** [comment]
Rails 4 doesn't seem to like this:

screen shot 2013-12-31 at 10 38 08 am

I also noticed this never made it to the gem either, I only found it by forking master and using it that way. Unless I'm just doing something terribly wrong.

**Comment by jherdman** [comment]
@alkrauss48 yeah, you're right. The `match` should be changed to a `get`.

**Pull request merged**
